### ISSUE TITLE
Caching mechanism for PHP

### ISSUE THREAD

**Issue by liaogz82** [aws/aws-secretsmanager-caching-python#15]
Hi, is there similar caching libraries for secretsmanage but is for PHP?

**Comment by eddielou** [comment]
Not at the moment. We currently have caching libraries available for Java, Go, C#, and Python. We have plans to release a caching library for PHP in the future, but we don't have a timeline for this yet.

**Comment by liaogz82** [comment]
How do I cache it in a meantime while waiting for your PHP library to be up?

**Comment by eddielou** [comment]
You could create a basic implementation of a Secret Cache, where you store the last known good value. If the last known good value of the secret doesn't work, then use GetSecretValue to retrieve the new good value.

Unfortunately, we don't have any PHP libraries that can offer similar functionality right now.

**Comment by rowiec** [comment]
Hi any update for PHP caching? I understand that it's been 2 years and hoping that there's already a caching library. thanks
