### ISSUE TITLE
Not able to read the Database secret

### ISSUE THREAD

**Issue by cpj2195** [aws/aws-secretsmanager-caching-python#18]
`import os
import boto3
import base64
from aws_secretsmanager_caching import SecretCache, SecretCacheConfig
import json
from botocore.exceptions import ClientError

def get_dbsecret():

    secret_name = os.getenv('DATABASE_SECRET')
    region_name = os.getenv('SECRETS_MANAGER_REGION')
    # Create a Secrets Manager client
    session = boto3.session.Session()
    client = session.client(
        service_name='secretsmanager',
        region_name=region_name
    )

    try:
        # Create a cache
        cache = SecretCache(SecretCacheConfig(),client)

        # Get secret string from the cache
        get_secret_value_response = cache.get_secret_string(secret_name)
        return get_secret_value_response
    except ClientError as e:
        if e.response['Error']['Code'] == 'DecryptionFailureException':
            # Deal with the exception here, and/or rethrow at your discretion.
            raise e
        elif e.response['Error']['Code'] == 'InternalServiceErrorException':
            # An error occurred on the server side.
            # Deal with the exception here, and/or rethrow at your discretion.
            raise e
        elif e.response['Error']['Code'] == 'InvalidParameterException':
            # You provided an invalid value for a parameter.
            # Deal with the exception here, and/or rethrow at your discretion.
            raise e
        elif e.response['Error']['Code'] == 'InvalidRequestException':
            # You provided a parameter value that is not valid for the current state of the resource.
            # Deal with the exception here, and/or rethrow at your discretion.
            raise e
        elif e.response['Error']['Code'] == 'ResourceNotFoundException':
            # We can't find the resource that you asked for.
            # Deal with the exception here, and/or rethrow at your discretion.
            raise e
    else:
        secret = client.get_secret_value(
            SecretId=secret_name
        )
        return secret
`

I have written the above code to read the secret name. The secret name and region are set as environment variables. When I invoke the above code, the function always returns a NONE value.
Am I doing anything wrong?

**Comment by jimathyp** [comment]
You're getting None because a ClientError is raised, but it is silently falling through the if/elif statements after 'except ClientError as e'. 

If you're really not doing anything with those ClientErrors in the if/elif blocks then just raise the exception after the except. 

Otherwise, add a final 'else' the if/elif statements because you're not catching every possible ClientError.

**Comment by danmancuso** [comment]
Thanks for the explanation @jimathyp!  That's most likely the case.  @cpj2195 I'm closing this case for now, but please feel free to open a new case if wanted!
