### ISSUE TITLE
required IAM permissions

### ISSUE THREAD

**Issue by ghukill** [aws/aws-secretsmanager-caching-python#19]
Not sure if it would be helpful to add to documentation, but I encountered a situation where I was pulling secrets successfully with the boto3 client, but ran into permissions issue when switching to using this library.

Specifically, I had success pulling secrets with a single IAM permission:
  * `secretsmanager:GetSecretValue`

But I realized the following is also required for this library:
  * `secretsmanager:DescribeSecret`

I don't know if it's feasible or possible to outline what IAM action permissions are needed, but it could be helpful for those migrating from using boto3 directly.  That said, thanks for a great library!

**Comment by parimaldeshmukh** [comment]
Thank you for opening this issue - we are looking into it.

**Comment by mvanbaak** [comment]
It's documented on https://docs.aws.amazon.com/secretsmanager/latest/userguide/use-client-side-caching.html#use-client-side-caching-components
