### ISSUE TITLE
InjectKeywordedSecretString - Not returning result

### ISSUE THREAD

**Issue by denniscmpe** [aws/aws-secretsmanager-caching-python#21]
When I use the InjectKeywordedSecretString decorator, it is preventing the decorated function from returning the result:

@InjectKeywordedSecretString(SECRET_NAME, SECRET_CACHE, aws_access_key_id="aws_access_key_id",
                             aws_secret_access_key="aws_secret_access_key")
def get_authorization(aws_region, aws_access_key_id, aws_secret_access_key) -> AWS4Auth:
    return AWS4Auth(aws_access_key_id, aws_secret_access_key, aws_region, "appsync")

**Comment by vatima2016** [comment]
The fix has been done by @ajbarry https://github.com/aws/aws-secretsmanager-caching-python/pull/17
But unfortunately nobody merges the pull request :-(

**Comment by rstevens011** [comment]
this has been merged and a PyPI release should be in the next day or two.

**Comment by rstevens011** [comment]
As a general note, I'd like to discourage you from storing IAM user credentials in Secrets Manager and would encourage you to use IAM roles as much as practicable.

**Comment by rstevens011** [comment]
Published to pypi: https://pypi.org/project/aws-secretsmanager-caching/1.1.1.5
