### ISSUE TITLE
Right way to implement caching

### ISSUE THREAD

**Issue by mohit2152sharma** [aws/aws-secretsmanager-caching-python#28]
Following the `README.md`, I have implemented caching. Essentially added the following the code:

``` python
session = boto3.session.Session()
client = session.client(
    service_name='secretsmanager',
    region_name=region_name
)
config=SecretCacheConfig()
cache = SecretCache(config=config, client=client)
secrets = cache.get_secret_string(secret_id=secret_id)
```
and removed the old code of how I was fetching the secrets i.e.

``` python
session = boto3.session.Session()
client = session.client(
    service_name='secretsmanager',
    region_name=region_name
)

secret_value_response = client.get_secret_value(
     SecretId=secret_id
)
```

The question I have is: Is it the right way to implement way caching? As it appears it doesn't seem to work. I am using this piece of code in a flask api server. Whenever I make the api call, the code uses secrets to fetch data from mysql db. What I have observed is at each API call, the `get_secret_string()` function is calling `_client.describe_secret()` ([this function](https://github.com/aws/aws-secretsmanager-caching-python/blob/ec907d5de637724c35e4df108617638462c0ec81/src/aws_secretsmanager_caching/cache/items.py#L201)). This function is adding time to API call and making overall response time of api high.

Please help

**Comment by DrCord** [comment]
All of my lambda runtimes increased dramatically as well doing the exact same thing as the OP. Please answer the question. My understanding is that implementing this should lower lambda execution time.
