### ISSUE TITLE
Missing dependency declaration for `setuptools`

### ISSUE THREAD

**Issue by itssimon** [aws/aws-secretsmanager-caching-python#48]
The `aws_secretsmanager_caching` package depends on the deprecated `pkg_resources` module in `setuptools` during runtime, but doesn't specify `setuptools` as a dependency. This leads to a `ModuleNotFoundError` unless the user explicitly adds `setuptools` as a dependency in their project.

https://github.com/aws/aws-secretsmanager-caching-python/blob/359b7dfe29798ec4ed71507c22f536fe44bfa762/src/aws_secretsmanager_caching/secret_cache.py#L18

```
  File "/app/.venv/lib/python3.12/site-packages/common/secrets.py", line 6, in <module>
    from aws_secretsmanager_caching import SecretCache, SecretCacheConfig
  File "/app/.venv/lib/python3.12/site-packages/aws_secretsmanager_caching/__init__.py", line 16, in <module>
    from aws_secretsmanager_caching.secret_cache import SecretCache
  File "/app/.venv/lib/python3.12/site-packages/aws_secretsmanager_caching/secret_cache.py", line 18, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by simonmarty** [comment]
We're going to track this with #42
